### ISSUE TITLE
Support button_tag?

### ISSUE THREAD

**Issue by elbarsal** [mois3x/sweet-alert-rails-confirm#13]
Wondering if you could add support for button_tag elements. Not sure if this is 100% correct, but the code below worked for me. If you prefer, I can put in a pull request.

    def button_tag(*args, &block)

      html_options = args[block_given? ? 0 : 1] || {}

      if options_has_confirm?(html_options)
        html_options['data-sweet-alert-confirm'] = html_options.delete(:confirm) ||
                    html_options[:data].delete(:confirm)
      end
      super *args, &block

    end

**Comment by mois3x** [comment]
Hi thanks check it out now with bundle update

**Comment by mois3x** [comment]
Closing this since it seems working with no problem
