### ISSUE TITLE
Why change title gem?

### ISSUE THREAD

**Issue by adrianoresende** [mois3x/sweet-alert-rails-confirm#20]
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'rails-assets-sweetalert (>= 0) ruby' in any of the gem sources listed in your
Gemfile or installed on this machine.

**Comment by mois3x** [comment]
Sorry, the name has not changed, only the instructions and dependencies. Now you can chose which gem you want to use to fetch the Sweetalert Assets. Before, the gem were dependent on https://github.com/Najtmare/sweet-alert-rails.

But that gem is not frequently updated. 

To use sweet-alert-rails-confirm in your gemfile:

load the assets of SweetAlert:

`gem 'sweet-alert'`
and the replacement for rails-confirm
`gem 'sweet-alert-confirm'`

With that is all done.

However if you wanna the latest version from SweetAlert js library you should replace `gem 'sweet-alert'` with: `gem 'rails-assets-sweetalert'` 

To use the last option you should check instructions on the page https://rails-assets.org/
