### ISSUE TITLE
couldn't find file 'sweet-alert-confirm'

### ISSUE THREAD

**Issue by tolerantx** [mois3x/sweet-alert-rails-confirm#40]
I'm trying to implement the gem with the readme instructions, in my Gemfile I have the following code:

```
source "https://rails-assets.org" do
  gem "rails-assets-sweetalert", "~> 1.1.3"
end
```

In my application.js

```
//= require sweetalert
//= require sweet-alert-confirm
```

But when I start my local server I get this error:

```
couldn't find file 'sweet-alert-confirm' with type 'application/javascript'
```

Any idea?

**Comment by mois3x** [comment]
you need to include the gem 'sweet-alert-confirm' at the bottom gemfile also.

**Comment by doncadavona** [comment]
I've followed the setup instructions, but I'm getting this:

`couldn't find file 'sweetalert' with type 'text/css'`

**Comment by carlosgomez2** [comment]
You need to change 'sweetalert' to 'sweet-alert' into css and js files

CSS:
`*= require sweet-alert`

JS:
`//= require sweet-alert`

**Comment by chinm3** [comment]
Hi, I added this sweet-alert and followed instructions, it doesn't seem to be showing the alert? My Bootstrap flash messages says "it's deleted though"...

**Comment by doncadavona** [comment]
Also, 

> **sweet-alert-confirm** of type text/javascript

 is not found.

**Comment by jbayotlang** [comment]
@doncadavona I think you need to restart your server after installing the Gem.
